miniProjects/minipro/auth/urls.py
from django.urls import path

from auth import views

app_name='auth'
urlpatterns =[
    path('login/', views.Login.as_view(),name='login'),
    path('logout/', views.Logout.as_view(),name='logout')
]

miniProjects/minipro/minipro/urls.py
from django.contrib import admin
from django.urls import path,include
from django .views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('auth.urls',namespace='auth')),
    path('timesheet/',include('timesheet.urls',namespace='timesheet')),
    path('',TemplateView.as_view(template_name='timecard.html'),name='timecard')
]

miniProjects/minipro/timesheet/urls.py
from django.urls import path

from timesheet import views

app_name='timesheet'
urlpatterns=[
    path('summary',views.TimeSheet.as_view(),name='summary'),
    path('timecard',views.addtimecard,name='timecard'),
    path('total_leaves',views.flaskView,name='total_leaves'),
    path('timecard1',views.create_timecard_with_project,name='timecard1'),
    path('employee',views.GetUsers.as_view(),name='employees'),
    path('employee/<int:pk>',views.GetUsesTimeCard.as_view(),name='employee'),


]

miniProjects/minipro/timesheet/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
import datetime
# Create your models here.
FUNCTION_TYPE=(
    ('DE','Data Engineering'),
    ('SE','Software Engineering'),
    ('TE','Testing'),
    ('DO','DevOps'),
)
FUNCTIONAL_LEADER =(
    ('RK','Ramesh Kumar'),
    ('NI','Naveen Iyer'),
    ('SN','Suresh Nair'),
    ('NV','Nitin Varma'),

)
PROJECT1_TYPE = (
    ('C','Corporate'),
    ('LS','Lending Stream'),
    ('D','Drafty'),

)
TEAM=(
    ('ST1','Sprint Team 1'),
    ('ST2','Sprint Team 2'),
    ('ST3','Sprint Team 3'),
)

MONTH=(
    (1,'JANUARY'),
    (2,'FEBRUARY'),
    (3,'MARCH'),
    (4,'APRIL'),
    (5,'MAY'),
    (6,'JUNE'),
    (7,'JULY'),
    (8,'AUGUST'),
    (9,'SEPTEMBER'),
    (10,'OCTOBER'),
    (11,'NOVEMBER'),
    (12,'DECEMBER'),

)
class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=25,null=True,blank=False)
    team=models.CharField(choices=TEAM,default='SE',max_length=25,null=True,blank=False)
    def __str__(self):
        return('{0}'.format(self.name))



class TimeCard(models.Model):
    date_created = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,unique_for_month="date_created")

    function=models.CharField(choices=FUNCTION_TYPE,default='DE',max_length=25,null=True,blank=False)
    functional_leader=models.CharField(choices=FUNCTIONAL_LEADER,default='RK',max_length=25,null=True,blank=False)
    leaves=models.PositiveIntegerField(default=0,null=True,)
    project1 = models.CharField(choices=PROJECT1_TYPE,default='C', max_length=25,null=True,blank=False)
    time_project1 = models.PositiveIntegerField(null=True,blank=False)

    total_time=models.PositiveIntegerField(null=True,blank=False)
    month=models.PositiveIntegerField(choices=MONTH,default=12)
    year=models.PositiveIntegerField(blank=False,default=2020)
    @property
    def Month(self):
        if self.date_created:
            return self.date_created.strftime("%B")
        return "No date entry"
    @property
    def Year(self):

        if self.date_created:
            return self.date_created.strftime("%Y")
        return "No date entry"

    def __str__(self):
        return('{0}-{1}'.format(self.date_created,self.user))


    def get_projects(self):
        return self.projects.all().values_list('project',flat=True)


    def get_projects_time(self):
        return self.projects.all().values_list('time_project',flat=True)
    class Meta:
        verbose_name= _('TimeCard')
        ordering = ['-date_created']

    def save(self, *args, **kwargs):
        #today=datetime.date.today()
        #self.month=today.month
        #self.year=today.year

        if TimeCard.objects.filter(month=self.month,year=self.year,user=self.user).exists():
            raise ValidationError("Already submitted")

        return super(TimeCard,self).save(*args, **kwargs)

class Project(models.Model):
    project = models.CharField(default='Drafty' ,max_length=25)
    time_project = models.PositiveIntegerField()
    timecard = models.ForeignKey(
        TimeCard,
        related_name='projects', on_delete=models.SET_NULL,
        null=True)



    def __str__(self):
        return self.project

miniProjects/minipro/timesheet/forms.py
from django import forms
from timesheet import models
from django.core.exceptions import ValidationError
from datetime import datetime
from django.forms import (formset_factory, modelformset_factory)

class TimeCardForm(forms.ModelForm):


    class Meta:
        model =models.TimeCard
        exclude=['user']

ProjectFormset = modelformset_factory(
    models.Project,
    fields=('project','time_project', ),
    extra=1,
    widgets={'project': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Project Name here'
        }),
        'time_project': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Time for Project  here'
        })
    }
)

'''
    def clean(self):
        cleaned_data = self.cleaned_data
        if models.TimeCard.objects.filter(date_created=datetime.now(),user=cleaned_data['user']).exists():
            raise ValidationError('Already Submited')

        # Always return cleaned_data
        return cleaned_data
'''

miniProjects/minipro/timesheet/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin
import requests
import json
from django.views.generic import(
    ListView,
    DetailView)
from timesheet import (
    models,
    forms
)
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class TimeSheet(LoginRequiredMixin,ListView):

    context_object_name = 'timecards'
    template_name = 'timesheet/summary.html'
    login_url= 'auth/login'

    def get_queryset(self):
        return models.TimeCard.objects.filter(user=self.request.user).order_by('-date_created')
'''
class AddTimeCard(View):
    timecardform = forms.TimeCardForm(request.POST)
    def get(self,request):
        context ={
            'timecardform' : timecardform
        }
        return render(request,'timesheet/timecard.html',context)
'''
class GetUsers(UserPassesTestMixin,LoginRequiredMixin,ListView):

    model=models.User
    template_name ='timesheet/user.html'
    def test_func(self):

        if self.request.user.is_superuser:
            return True
        else:
            return False


class GetUsesTimeCard(UserPassesTestMixin,LoginRequiredMixin,DetailView):

    model=models.User
    template_name ='timesheet/time_list.html'

    def test_func(self):

        if self.request.user.is_superuser:
            return True
        else:
            return False

def create_timecard_with_project(request):
    if not request.user.is_authenticated:
        return redirect('auth:login')
    template_name = 'timesheet/timecard1.html'
    if request.method == 'GET':
        timecardform = forms.TimeCardForm(request.GET or None)
        formset = forms.ProjectFormset(queryset=models.Project.objects.none())
    elif request.method == 'POST':
        timecardform = forms.TimeCardForm(request.POST)
        formset = forms.ProjectFormset(request.POST)
        if timecardform.is_valid() and formset.is_valid():

            timecard = timecardform.save(commit=False)
            user = request.user
            timecard.user = user
            try:
                timecard.save()
            except:
                messages.error(request, 'Time Card Already Submitted for Month')
                return redirect('timesheet:timecard1')

            for form in formset:

                project = form.save(commit=False)
                project.timecard = timecard
                project.save()
            messages.success(request, 'Time Card submitted')
            return redirect('timesheet:summary')
        messages.error(request, 'Failed to submit Time Card')
        return redirect('timesheet:timecard1')

    return render(request, template_name, {
        'timecardform': timecardform,
        'formset': formset,
        'title':'Time Card'
    })

def flaskView(request):
    if not request.user.is_authenticated:
        return redirect('auth:login')
    if not request.user.is_superuser:
        return redirect('timesheet:timecard')
    template_name ='timesheet/leave.html'
    response=requests.get('http://127.0.0.1:5000/')
    mydict={}


    result=[]
    for ele in response.json():
        result.append((ele["name"],ele["sum(timesheet_timecard.leaves)"]))
    mydict['leaves']=result
    return render(request,template_name,mydict)

def addtimecard(request):

    if not request.user.is_authenticated:
        return redirect('auth:login')

    if request.method =='POST':
        form = forms.TimeCardForm(request.POST)
        if form.is_valid():
            instance =form.save(commit=False)
            user=request.user
            instance.user=user
            try:
                instance.save()
            except:
                messages.error(request, 'Time Card Already Submitted for Month')
                return redirect('timesheet:timecard')

            messages.success(request,'Time Card submitted')
            return redirect('timesheet:summary')
        messages.error(request,'Failed to submit Time Card')
        return redirect('timesheet:timecard')
    dataset=dict()
    form=forms.TimeCardForm()
    dataset['form']=form
    dataset['title']='Time Card'
    return render(request,'timesheet/timecard.html',dataset)

miniProjects/minipro/templates/timesheet/leave.html
{% extends 'base.html' %}

{% block content %}
        <div class='container'>
        <div class='row'>
            <h1>Total Leaves by Employees</h1>
        </div>
        <div class='row'>
            <div class="col-6">

                    <ul class="collection">


                        <li class="collection-item">Name Of Employee      -----         Total Number of Leaves </li>
                       {% for name,leave in leaves %}
                        <li class="collection-item">{{name}}     {{leave}}</li>

                        {% endfor %}
                        </ul>


            </div>



        </div>

    </div>
</div>
{% endblock %}

miniProjects/minipro/templates/timesheet/summary.html
{% extends 'base.html' %}

{% block content %}


    {% for timecard in timecards %}
        {% include 'timesheet/component/card.html' %}
    {% endfor %}

{% endblock %}

miniProjects/minipro/templates/timesheet/time_list.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
    <div class="col-6">
            <div class="row">
                <h1>
                    {{user.username}}
                 </h1>
            </div>
    </div>
    </div>

    {% for timecard in user.timecard_set.all %}
        {% include 'timesheet/component/card.html' %}
    {% endfor %}

{% endblock %}

miniProjects/minipro/templates/timesheet/timecard.html
    {% extends 'base.html' %}
    {% block stylesheet %}
    .container{
    height:1000px;
    }
    {% endblock %}

    {% block content %}
    <div class="row" xmlns:>
                <div class="col s7 offset-s3 ">
                  <div class="card">



                          {% if messages %}
                                {% for message in messages %}
                                <div {% if message.tags %} class="'{{messages.tags}}"{% endif %}>
                                     <p style="color:red;font-size:30px">
                                         {{message}}
                                     </p>

                                 </div>
                                {% endfor %}
                            {%endif%}
                      </div>

                          </div>





                  </div>

        <div class="container">
             <div class="row">
                <div class="col s6 offset-s3 ">
                  <div class="card">

                      <form method="POST" class="card">
                          <div class="card-content ">
                            <span class="card-title">Time Card</span>

                             {% csrf_token %}
                             <div id="forms">
                                {{ form.as_p }}
                            </div>
                          </div>
                           <div class="card-action">
                              <button class="waves-effect waves-light btn" type="submit" >Submit</button>
                           </div>



                        </form>


                  </div>
                </div>
              </div>
                </div>


    {% endblock %}
<script>

miniProjects/minipro/templates/timesheet/timecard1.html
{% extends "base1.html" %}

{% block container %}
<div class="card" style="width: 50rem;">

  <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                <div {% if message.tags %} class="'{{messages.tags}}"{% endif %}>
                                    <p style="color:red;font-size:30px">
                                         {{message}}
                                     </p>

                                 </div>
                                {% endfor %}
                            {%endif%}
        </div>
    </div>
<div class="card text-white bg-dark mb-3 text-center" style="width: 60rem;" >

  <div class="card-body">




<form class="form-horizontal" method="POST" action="">
    {% csrf_token %}
<div class="row spacer">
                             <div class="form" >
                                {{ timecardform.as_p }}
                            </div>
</div>

{{ formset.management_form }}
{% for form in formset %}
<div class="row form-row spacer">
    <div class="col-2">
        <label>{{form.project.label}}</label>
    </div>
    <div class="col-4">
        <div class="input-group">
            {{form.project}}
            <div class="input-group-append">
                <button class="btn btn-success add-form-row">+</button>
            </div>
        </div>
    </div>
        <div class="col-2">
        <label>{{form.time_project.label}}</label>
    </div>
    <div class="col-4">
        <div class="input-group">
            {{form.time_project}}
            <div class="input-group-append">
                <button class="btn btn-success add-form-row">+</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}


<div class="row spacer">
    <div class="col-4 offset-1">
        <button type="submit" class="btn btn-block btn-primary">Create</button>
    </div>
</div>

</form>
   </div>
    </div>

{% endblock %}

{% block custom_js %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="text/javascript">
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+)');
    var replacement = prefix + '-' + ndx;
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
}
function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
    newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
        var name = $(this).attr('name')
        if(name) {
            name = name.replace('-' + (total-1) + '-', '-' + total + '-');
            var id = 'id_' + name;
            $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
        }
    });
    newElement.find('label').each(function() {
        var forValue = $(this).attr('for');
        if (forValue) {
          forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
          $(this).attr({'for': forValue});
        }
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    var conditionRow = $('.form-row:not(:last)');
    conditionRow.find('.btn.add-form-row')
    .removeClass('btn-success').addClass('btn-danger')
    .removeClass('add-form-row').addClass('remove-form-row')
    .html('-');
    return false;
}
function deleteForm(prefix, btn) {
    var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (total > 1){
        btn.closest('.form-row').remove();
        var forms = $('.form-row');
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        for (var i=0, formCount=forms.length; i<formCount; i++) {
            $(forms.get(i)).find(':input').each(function() {
                updateElementIndex(this, prefix, i);
            });
        }
    }
    return false;
}
$(document).on('click', '.add-form-row', function(e){
    e.preventDefault();
    cloneMore('.form-row:last', 'form');
    return false;
});
$(document).on('click', '.remove-form-row', function(e){
    e.preventDefault();
    deleteForm('form', $(this));
    return false;
});

</script>
{% endblock %}

miniProjects/minipro/templates/timesheet/user.html
{% extends 'base.html' %}

{%block content %}
    <div class='container'>
        <div class='row'>
            <h1>Employees</h1>
        </div>
        <div class='row'>
            <div class="col-6">
                <div class="collection">
                    {% for candidate in user_list %}
                    <a href="{% url 'timesheet:employee' candidate.id %}" class="collection-item">{{candidate.username}}</a>

                    {%endfor%}
                </div>

            </div>



        </div>

    </div>

{% endblock %}