miniProjects/minipro/auth/urls.py
from django.urls import path

from auth import views

app_name='auth'
urlpatterns =[
    path('login/', views.Login.as_view(),name='login'),
    path('logout/', views.Logout.as_view(),name='logout')
]

miniProjects/minipro/minipro/urls.py
from django.contrib import admin
from django.urls import path,include
from django .views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('auth.urls',namespace='auth')),
    path('timesheet/',include('timesheet.urls',namespace='timesheet')),
    path('',TemplateView.as_view(template_name='timecard.html'),name='timecard')
]

miniProjects/minipro/timesheet/urls.py
from django.urls import path

from timesheet import views

app_name='timesheet'
urlpatterns=[
    path('summary',views.TimeSheet.as_view(),name='summary'),
    path('timecard',views.addtimecard,name='timecard'),
    path('total_leaves',views.flaskView,name='total_leaves'),
    path('timecard1',views.create_timecard_with_project,name='timecard1'),
    path('employee',views.GetUsers.as_view(),name='employees'),
    path('employee/<int:pk>',views.GetUsesTimeCard.as_view(),name='employee'),


]

miniProjects/minipro/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>


        <title>TimeSheet</title>



    <!-- Compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
      $(document).ready(function(){
        $('select').formSelect();
      });
    </script>
    <!-- Compiled and minified CSS -->
    <meta name = "viewport" content = "width = device-width, initial-scale = 1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel = "stylesheet"
         href = "https://fonts.googleapis.com/icon?family=Material+Icons">

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <!--
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <style type="text/css">
        .spacer{
            margin-top:25px;
        }
    </style>-->
    {% block head %}
   <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Time Sheet</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          {% if request.user.is_superuser %}
            <li><a href="{% url 'auth:logout' %}">Logout</a></li>
            <li><a href="{% url 'timesheet:timecard'%}">Timecard</a></li>
            <li><a href="{% url 'timesheet:summary'%}">Summary</a></li>
          <li><a href="{% url 'timesheet:employees'%}">Users</a></li>
          <li><a href="{% url 'timesheet:total_leaves'%}">Total Leaves</a></li>
          {% elif request.user.is_authenticated %}

            <li><a href="{% url 'auth:logout'%}">Logout</a></li>
            <li><a href="{% url 'timesheet:timecard'%}">Timecard</a></li>
            <li><a href="{% url 'timesheet:timecard1'%}">Timecard1</a></li>
            <li><a href="{% url 'timesheet:summary'%}">Summary</a></li>

          {% else %}
          ` <li><a href="">Login</a></li>
          {% endif %}
      </ul>
    </div>
  </nav>
        {%endblock%}
    </head>
    <body>
        {% block content %} {%endblock%}

    {% block custom_js %}{% endblock %}
    </body>
</html>

miniProjects/minipro/templates/base1.html
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <style type="text/css">
        .spacer{
            margin-top:25px;
        }
    </style>
    {% block custom_css %}{% endblock %}
    <title>Timesheet</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Time Sheet</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'timesheet:summary'%}">Summary <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'timesheet:timecard1'%}">TimeCard<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'auth:logout'%}">Logout <span class="sr-only">(current)</span></a>
                </li>

            </ul>
        </div>
    </nav>



    <div class="container">
        <div class="row spacer"></div>
        <div class="row offset-2">
            <div class="col-12">
                {% block container %}
                {% endblock %}
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% block custom_js %}{% endblock %}
</body>

</html>